config/routes.rb
SimpleNewsline::Application.routes.draw do
  devise_for :users

  resources :articles do
    get :rating_articles, on: :collection
    get :user_articles, on: :collection
  end

  root :to => 'articles#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)

    if user.role? :user
      can :new, Article
      can :create, Article
      can :show, Article
      can :index, Article
      can :destroy, Article
      can :update, Article
      can :edit, Article
      can :rating_articles, Article

    else
      can :index, Article
      can :show, Article

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
    end
  end
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :rating, :text, :title, :user_id

  validate :title, :text, presence: true
  validate :title, length: { in: 10..80 }

  belongs_to :user
  has_many :vote_to_articles

  def vote_and_rating(current_user,params)
    if (params == 1)
      self.rating = self.rating + 1
      self.save
    else
      self.rating = self.rating - 1
      self.save
    end
    vote = self.vote_to_articles.create
    vote.user_id = current_user.id
    vote.save
  end

end

app/models/role.rb
class Role < ActiveRecord::Base
  attr_accessible :name, :role_ids

  has_and_belongs_to_many :users

end

app/models/roles_users.rb
class RolesUsers < ActiveRecord::Base
  attr_accessible :role_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :setup_role
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :role_ids
  # attr_accessible :title, :body

  has_many :articles
  has_and_belongs_to_many :roles

  def role?(role)
    return !!self.roles.find_by_name(role.to_s)
  end

# Установка роли по id. В конкретном случае использование данного подхода обосновано.
# id:1 - user
  private
  def setup_role
    if self.role_ids.empty?
      self.role_ids = [1]
    end
  end

end

app/models/vote_to_article.rb
class VoteToArticle < ActiveRecord::Base
  attr_accessible :article_id, :user_id

  belongs_to :article

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  rescue_from CanCan::AccessDenied do |exception|
    flash[:alert] = exception.message
    redirect_to root_url
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  load_and_authorize_resource :except => [:index, :show]
  before_filter :article_find, :only => [:show, :edit, :update, :destroy, :rating_articles, :its_article?]
  before_filter :its_article?, :only => [:edit, :update, :destroy]
  # GET /articles
  # GET /articles.json
  def index
    if params[:type].to_i == 2
      # Сортировка по рейтингу
      @articles_page = Article.paginate(page: params[:page], order: 'rating desc', per_page: 30)
    else
      # Сортировка по дате создания
      @articles_page = Article.paginate(page: params[:page], order: 'created_at desc', per_page: 30)
    end

    respond_to do |format|
      format.js
      format.html # index.html.erb
    end
  end

  # GET /articles/1
  # GET /articles/1.json
  def show

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /articles/new
  # GET /articles/new.json
  def new
    @article = Article.new

    respond_to do |format|
      format.html # new.html.slim
    end
  end

  # GET /articles/1/edit
  def edit

  end

  # POST /articles
  # POST /articles.json
  def create
    @article = current_user.articles.create(params[:article])

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /articles/1
  # PUT /articles/1.json
  def update

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
    end
  end

  def rating_articles
    @article.vote_and_rating(current_user,params[:rating].to_i)

    respond_to do |format|
      format.js
    end
  end

  def user_articles
    @articles = current_user.articles

    respond_to do |format|
      format.html #{ redirect_to  }
    end
  end

# Возможность удалять и редактировать только свои статьи
  private
  def its_article?
    if @article.user_id != current_user.id
      return redirect_to root_path
    end
  end

  def article_find
    @article = Article.find(params[:id].to_i)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def vote_user_to_articles(articles)
    @vote = VoteToArticle.where("article_id=? and user_id=?",articles,current_user)
    if @vote.present?
      false
    else
      true
    end
  end
end

app/views/articles/_articles_orderby.html.slim
table class="table table-striped table-condensed"
  tr
    th Заголовок
    th Дата создания
    th Рейтинг
  - @articles_page.each do |articles|
    tr
      td = link_to articles.title, articles
      td = articles.created_at
      td = articles.rating
br
= will_paginate @articles_page

app/views/articles/_form.html.slim
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      h2 = "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      ul
        - @article.errors.full_messages.each do |message|
          li = message

  .field
    = f.text_field :title, :placeholder => "Заголовок..", :class => "form-control"
  br
  .field
    = f.text_area :text, :placeholder => "Текст новости..", :class => "form-control"
  br
  .actions = f.submit 'Сохранить', :class=> "btn"

app/views/articles/_update_rating.html.slim
| &nbsp;
small Рейтинг новости:
small
  '
  = @article.rating

app/views/articles/edit.html.slim
h3 Редактировать новость
br
div.col-md-4
  == render 'form'

  br
  = link_to 'Просмотреть новость', @article
  ' &nbsp;|
  = link_to 'На главную', root_path

app/views/articles/index.html.slim
h3 style="text-align:center;" Все новости
div
  = link_to "Свежие новости", "/?type=1", :class => "active", :id => "fresh", :remote => true
  ' &nbsp;|
  = link_to "Лучшие новости", "/?type=2", :id => "best", :remote => true

div.well
  = render "articles/articles_orderby"

app/views/articles/index.js.erb
$("div.well").html("<%= j(render('articles_orderby', :articles => @articles)) %>");
$("#fresh").toggleClass("active");
$("#best").toggleClass("active");

app/views/articles/new.html.slim
h3  Добавить новость
br
div.col-md-4
  == render 'form'
  br
  = link_to 'На главную', root_path

app/views/articles/rating_articles.js.erb
$("#rating_div").html("<%= j(render('update_rating', @articles)) %>");
$(".voterating").hide();

app/views/articles/show.html.slim
p#notice = notice

div class="thumbnail"
  div class="caption-full"
    h4 class="pull-right" = @article.user.email
    h4
      a href="#" = @article.title
      br
      div#rating_div
        | &nbsp;
        small Рейтинг новости:
        small
          '
          = @article.rating
    p
      = @article.text
    div class="bottom"
      p class="pull-right"
        = @article.created_at
        br
        - if (can? :edit, @article and @article.user_id == current_user.id)
          = link_to 'Редактировать новость', edit_article_path(@article)
          br
        - if (can? :destroy, @article and @article.user_id == current_user.id)
          = link_to 'Удалить новость', @article, :confirm => 'Вы уверены?', :method => :delete
    br
    br
    br
    div.voterating style="text-align:center;"
      - if can? :rating_articles, @article
        - if (vote_user_to_articles(@article.id))
          div
            br
            | Оцените новость:
            br
            = link_to("-1", :controller=>"articles", :action=> "rating_articles", :id => @article.id, :rating => 0, :remote => true)
            | &nbsp; ... &nbsp;
            = link_to("+1", :controller=>"articles", :action=> "rating_articles", :id => @article.id, :rating => 1, :remote => true)
br
= link_to 'На главную', root_path

app/views/articles/user_articles.html.slim
h3 style="text-align:center;" Мои новости

div.well
  table class="table table-striped table-condensed"
    tr
      th Заголовок
      th Дата создания
      th Рейтинг
      th
      th
    - @articles.each do |articles|
      tr
        td = link_to articles.title, articles
        td = articles.created_at
        td = articles.rating
        - if (can? :edit, articles and articles.user_id == current_user.id)
          td = link_to 'Редактировать новость', edit_article_path(articles)
        - if (can? :destroy, articles and articles.user_id == current_user.id)
          td = link_to 'Удалить новость', articles, :confirm => 'Вы уверены?', :method => :delete

app/views/layouts/application.html.slim
html
  head
  title SimpleNewsline
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

  body
    nav class="navbar navbar-inverse navbar-fixed-top" role="navigation"
      div class="container"
        div class="navbar-header"
          button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse"
            span class="sr-only" Toggle navigation
            span class="icon-bar"
            span class="icon-bar"
            span class="icon-bar"
          a class="navbar-brand" href="/" Newsline

        div class="collapse navbar-collapse navbar-ex1-collapse"
          ul class="nav navbar-nav"
            - if user_signed_in?
              li class="dropdown"
                a href="#" class="dropdown-toggle" data-toggle="dropdown"
                  = current_user.email
                  b class="caret"
                ul class="dropdown-menu"
                  li = link_to 'Мои новости', user_articles_articles_path
                  li = link_to 'Добавить новость', new_article_path
                  li = link_to 'Выйти', destroy_user_session_path, :method => :delete
            - else
              li = link_to 'Войти', new_user_session_path
              li = link_to 'Зарегистрироваться', new_user_registration_path
    div.container
      = yield